services:
  db:
    image: mysql:8.0
    command:
      - --log-bin=mysql-bin
      - --binlog-expire-logs-seconds=3600  # Удалять логи через 1 час
      - --max-binlog-size=100M
    container_name: shortlify_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortlify_development
      MYSQL_USER: shortlify
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: .
    container_name: shortlify_backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://shortlify:password@db:3306/shortlify_development
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_WITHOUT: ""
      SECRET_KEY_BASE: "a432ed34761f82b6d1bed32300881498401e80c05d02efc9abbbb41e49549f77d20900aacf86799dd440de21a19ab8e234117ce798f62560340e6e25ac8a621c"
      RAILS_SECRET_KEY_BASE: "a432ed34761f82b6d1bed32300881498401e80c05d02efc9abbbb41e49549f77d20900aacf86799dd440de21a19ab8e234117ce798f62560340e6e25ac8a621c"
      JWT_SECRET: "a432ed34761f82b6d1bed32300881498401e80c05d02efc9abbbb41e49549f77d20900aacf86799dd440de21a19ab8e234117ce798f62560340e6e25ac8a621c"
      

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shortlify_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1 # Используем имя сервиса
      - NEXT_PUBLIC_BASE_URL=http://localhost:3001
      - NEXT_PUBLIC_CHAT_SERVER_URL=http://localhost:3002 # Для браузера используем localhost
      - NEXT_PUBLIC_WS_URL=ws://localhost:3002
    depends_on:
      - backend
    command: npm run dev -- --port 3000 --hostname 0.0.0.0

  redis:
    image: redis:7-alpine
    container_name: shortlify_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    container_name: shortlify_chat_server
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: "production"
      PORT: "3002"
      RAILS_SECRET_KEY_BASE: "a432ed34761f82b6d1bed32300881498401e80c05d02efc9abbbb41e49549f77d20900aacf86799dd440de21a19ab8e234117ce798f62560340e6e25ac8a621c"
      JWT_SECRET: "a432ed34761f82b6d1bed32300881498401e80c05d02efc9abbbb41e49549f77d20900aacf86799dd440de21a19ab8e234117ce798f62560340e6e25ac8a621c"
      REDIS_URL: "redis://redis:6379"
      FRONTEND_URL: "http://localhost:3001"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./chat-server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  db_data:
  bundle_cache:
  redis_data: