services:
  db:
    image: mysql:8.0
    container_name: shortlify_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortlify_development
      MYSQL_USER: shortlify
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: .
    container_name: shortlify_backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://shortlify:password@db:3306/shortlify_development
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_WITHOUT: ""

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shortlify_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1
      - NEXT_PUBLIC_BASE_URL=http://localhost:3001
    depends_on:
      - backend
    command: npm run dev -- --port 3000

volumes:
  db_data:
  bundle_cache: